name: 📄 Documentation issue
description: Found an issue in the documentation? You can use this one!
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        **Hey Geek !!!** 

        This is an open source repository.

        * For questions, ask in [Discussions](https://github.com/codinasion/codinasion-programme/discussions).
        * Before you file an issue read the [Contributing guide](https://github.com/codinasion/codinasion-programme/blob/master/CONTRIBUTING.md).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/codinasion/codinasion-programme/issues).

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
